



SELECT A.CODIGO,A.NOME,A1.CGC,A.REPRES,A.MISTO FROM AREAS A INNER JOIN VW_WEBUSUARIO B ON A.CODIGO = B.COD_VEN
INNER JOIN CLIENTES A1 ON A.COD_CLI = A1.XCLIENTES AND ISNULL(A.ATIVO,'N')='N' AND B.HABILITADO='S'
AND A.REPRES='S'
ORDER BY A.CODIGO


SELECT * FROM MULT_ICM
WHERE CHAVE = 35026911

sp_status_nfe 0


SELECT H_VERAO FROM EMPRESAS WHERE CODIGO IN (47,48)




SELECT D.DOC,    

            SELECT B.SERIE, 

         B.NF_COMPL,B.USA_CLICM,B.COD_ICM AS 'MCOD_ICM',B.USA_CST,B.COD_TRI,B.ESTOQUE,B.SERVICO,B.SEM_SERV,
         B.USA_CONTA,B.COD_PAG,B.CCUSTO,B.JOB,B.USA_SCC,B.USA_JOB,b.OBS_DEF,B.USA_IPI_EM,IPI_EMBUTI,B.REPASSE_ZF,B.IMPOSTOS,
         B.ICMS_DEST,B.ALQ_ISS,B.ALQ_IRRF,B.ICM_NINC,B.NOP1,B.NOP1S,B.NOP2,B.NOP2S,B.NOP3,B.BONIF, B.CONTRA_PAR,
         B.MAT_PROMO, B.PRD_GRATIS, 
         C.CST_01,C.PERC_SERV,C.FAMILIA,C.PESO,C.PESO_L,C.REPASSE_ZF,C.USA_MIDIA,C.MIDIA,C.CESTA_SN,C.CONTEUDO,C.UNI_PESO,
         C.DIFISA_OF,C.DIFISA_SIM,C.AMOSTRA, 
         A.NRECNO,A.UM,A.CODRESERVA,A.PED,A.DATA,A.EMPRESA,A.QUAN,A.TIPO,A.CHAVE_PED,A.CARGA,A.CODIGO,
         A.COD_FIS,A.COD_ICM,A.COD_SER,A.LIN1,A.LOCAL,A.PESO,A.TIPO,A.UNID,A.VALOR_PRES,A.VALOR_UNI,A.DESCTO,A.SCC,A.JOB,
         A.FRETE_UNIT,A.COD_TRI, C.GENERICO,'' AS COMPL_MACRO,A.PER_COMIS, A.PERC_0, A.PERC_1, A.PERC_2, A.PERC_3, A.PERC_4, ISNULL(B.ISEN_SUBST,'N'), 
         A.PER_COMIS2, B.USA_CLLOC,A.QUAN_ORC, isnull(C.SUSPISCOF,'N'), B.CST_PIS, B.CST_COFINS,B.SUSPISCOF, ISNULL(B.SUS_STPIS,'09'), ISNULL(B.SUS_STCOF,'09'), B.SUS_OBSPC, B.CF_PISCOF,B.SN_PISCOFI 
	         , C.REDUZ_ICM, C.MSP, C.USA_STKG, C.STKILO, ISNULL(B.CONV54,'N'), C.PET_MALTA, B.PET_MALTA, ISNULL(A.FRETE_EMB,0), convert(int,ISNULL(C.CST_01,'0')), C.TAB, B.NOP2EC87 
         
             FROM MOV_PED A WITH(NOLOCK),MACRO B WITH(NOLOCK),GERAL C WITH(NOLOCK) WHERE PED='P2370319  ' AND
            A.COD_SER=B.CODIGO  AND A.CODIGO=C.CODIGO AND B.SERIE='C5RM1'
         
          ORDER BY A.PED,A.CODIGO,A.COD_PAI 


		  SELECT STATUS,* FROM MESSE_NFE.NFE.TB_SAIDA WHERE ChaveIntegracao = 35026911

		  SP_STATUS_NFE 0

		  SELECT * FROM MTF_FISCAL 
		  WHERE CHAVE = 35026911

		  
		  SELECT * FROM MULT_ICM
		  WHERE CHAVE = 35026911


		  SELECT * FROM NFE_LOG_RETORNO
		  WHERE CHAVE = 35026911

		  UPDATE NFE_LOG_RETORNO SET REENVIO=NULL
		  WHERE CHAVE = 35026911







		  SELECT AL_INTERNA, PROT_2604, AL_ICMS, ICM_DEF FROM ICMS_UF WITH(NOLOCK) WHERE UF='sp'

		 select * from PEDSERIE
		 where PED ='P2370319  '

		 SELECT PED FROM MOV_CON WHERE CHAVE =35027129

	  SELECT CHAVE,PED,VALOR_TOT,* FROM PAGREC
	  WHERE CHAVE =35027129

	  SELECT COD_SER FROM PEDIDO WHERE PED ='P2370319  '