

procura_procs'01/'


EXEC FILES_SMILE_BI_NOVO'02/01/2019','02/21/2019'


sp_helptext ATUALIZA_DADOS_CUBO_DESPESAS

DECLARE @HOJE SMALLDATETIME
DECLARE @ONTEM SMALLDATETIME
DECLARE @DATA_INI SMALLDATETIME
DECLARE @DATA_FIM SMALLDATETIME
DECLARE @MESATU INT
DECLARE @MESANT INT

SET @HOJE = CONVERT(VARCHAR(10),GETDATE() ,101)  
SET @ONTEM = CONVERT(VARCHAR(10),GETDATE()-1 ,101)  
--SET @HOJE = CONVERT(VARCHAR(10),'02/01/2019' ,101)  
--SET @ONTEM = CONVERT(VARCHAR(10),'01/31/2019' ,101)  
SET @MESATU=MONTH(@HOJE)
SET @MESANT=MONTH(@ONTEM)

--SELECT @MESATU,@MESANT

IF @MESATU=@MESANT
BEGIN
	SET @DATA_INI = DBO.ZEROSESQUERDA(CONVERT(VARCHAR(2),MONTH(@HOJE)),2) + '/01/' + CONVERT(VARCHAR(4),YEAR(@HOJE))  
	SET @DATA_FIM =CONVERT(VARCHAR(10),@ONTEM ,101)  
END
ELSE
BEGIN
	SET @DATA_INI = DBO.ZEROSESQUERDA(CONVERT(VARCHAR(2),MONTH(@ONTEM)),2) + '/01/' + CONVERT(VARCHAR(4),YEAR(@ONTEM))  
	SET @DATA_FIM =CONVERT(VARCHAR(10),@ONTEM ,101)  
END

EXEC FILES_SMILE_BI_NOVO @DATA_INI,@DATA_FIM