DECLARE @DATA_INI VARCHAR(10)
DECLARE @DATA_FIM VARCHAR(10)
SET @DATA_INI = CONVERT(DATE,DateAdd(mm, DateDiff(mm,0,GetDate()) , 0),112) 
SET @DATA_FIM = CONVERT(DATE,GETDATE()-1,100)
SET @DATA_INI = '07/01/2016'
SET @DATA_FIM = '10/31/2018'

DECLARE @str_NomeArquivo varchar(max)
DECLARE @str_NomeArquivo2 varchar(max)
DECLARE @str_NomeArquivo3 varchar(max)
DECLARE @str_comandocab VARCHAR(8000)
DECLARE @str_comando NVARCHAR(MAX)
DECLARE @str_comando2 NVARCHAR(MAX)
DECLARE @WORKDIR VARCHAR(200)
DECLARE @sql VARCHAR(200)   


--IF OBJECT_ID('TEMPDB.DBO.##PAGREC') IS NOT NULL DROP TABLE ##PAGREC
SET @WORKDIR = '\\srv-sql-hml\d$\Temp\SMILE_BI\'
SET @str_NomeArquivo=@WORKDIR+'CAB_PAGREC.CSV'
SET @str_NomeArquivo2=@WORKDIR+'DADOS.CSV'
SET @str_NomeArquivo3=@WORKDIR+'PAGREC.CSV'

SET @str_comando = 'SELECT '''
SELECT @str_comando += ''+(RTRIM(A.NAME)+';')  from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'PAGREC' ) 


SET @str_comando = LEFT(@STR_COMANDO,LEN(@STR_COMANDO)-1)

select @str_comando = @str_comando + ''''

SET @str_comandocab = 'bcp " '+@str_comando
SET @str_comandocab = @str_comandocab + ' " '
SET @str_comandocab = @str_comandocab + ' queryout ' + @str_NomeArquivo + ' -c -t  -T';
Exec xp_cmdshell @str_comandocab 

---- AGORA BUSCA O CONTEUDO
/*
SET @str_comando = ''
SET @str_comando += ' SELECT '
SELECT @str_comando += case when RTRIM(LTRIM(b.name)) in ('char','varchar') then 'ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM('+A.NAME+' Collate SQL_Latin1_General_CP1253_CI_AI))),'''') AS '+A.NAME ELSE 
CASE WHEN RTRIM(LTRIM(b.name)) in ('text') THEN 'ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO((('+A.NAME+'))),'''') AS '+A.NAME ELSE A.NAME END END +' ,'  from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'PAGREC' ) 
SET @str_comando = +LEFT(@STR_COMANDO,LEN(@STR_COMANDO)-1)
SET @str_comando += ' INTO ##PAGREC '
--SET @str_comando = @str_comando + ' FROM NEWAGE.DBO.PAGREC WHERE DATA_EMIS>=''06/28/2018'' and DATA_EMIS<=''06/28/2018''  '
SET @str_comando = @str_comando + ' FROM NEWAGE.DBO.PAGREC WHERE DATA_EMIS>='''+@DATA_INI+''' AND DATA_EMIS<='''+@DATA_FIM+''''
SELECT @str_comando
*/


SET @str_comando = ''
SET @str_comando += ' SELECT '
SELECT @str_comando += case when RTRIM(LTRIM(b.name)) in ('char','varchar') then 'ISNULL(NEWAGE.DBO.[RemoveExtraChars](RTRIM(LTRIM('+A.NAME+' Collate SQL_Latin1_General_CP1253_CI_AI))),'''') AS '+A.NAME ELSE 
CASE WHEN RTRIM(LTRIM(b.name)) in ('text') THEN 'ISNULL(NEWAGE.DBO.[RemoveExtraChars]((('+A.NAME+'))),'''') AS '+A.NAME ELSE A.NAME END END +' ,'  from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'PAGREC' ) 
SET @str_comando = +LEFT(@STR_COMANDO,LEN(@STR_COMANDO)-1)
SET @str_comando += ' INTO ##PAGREC '
--SET @str_comando = @str_comando + ' FROM NEWAGE.DBO.PAGREC WHERE DATA_EMIS>=''06/28/2018'' and DATA_EMIS<=''06/28/2018''  '
SET @str_comando = @str_comando + ' FROM NEWAGE.DBO.PAGREC WHERE DATA_EMIS>='''+@DATA_INI+''' AND DATA_EMIS<='''+@DATA_FIM+''''
SELECT @str_comando
--EXECUTE SP_EXECUTESQL @str_comando

/*
SET @str_comando2 = ''
SET @str_comando2 += ' bcp " SELECT TOP 100 '
SELECT @str_comando2 += case when RTRIM(LTRIM(b.name)) in ('NUMERIC','INT') then 'RTRIM(LTRIM(CONVERT(CHAR,'+A.NAME+'))) AS '+A.NAME ELSE 
A.NAME END +' ,'  from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'PAGREC' ) 
SET @str_comando2 = +LEFT(@STR_COMANDO2,LEN(@STR_COMANDO2)-1)
SET @str_comando2 = @str_comando2 + ' FROM ##PAGREC " '
SET @str_comando2 = @str_comando2 + ' queryout ' + @str_NomeArquivo2 + ' -c -t ";" -T';
select LEN(@str_comando2)
select @str_comando2
--Exec xp_cmdshell @str_comando2 
*/

---- AGORA BUSCA O CONTEUDO
SET @str_comando2 = ''
SET @str_comando2 += ' bcp " SELECT '
SELECT @str_comando2 += case when RTRIM(LTRIM(b.name)) in ('NUMERIC','INT') then 'RTRIM(LTRIM(CONVERT(CHAR,'+A.NAME+'))) AS '+A.NAME ELSE 
A.NAME END +' ,'  from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'PED_CORTE' ) 
SET @str_comando2 = +LEFT(@STR_COMANDO2,LEN(@STR_COMANDO2)-1)
SET @str_comando2 = @str_comando2 + ' FROM ##PAGREC " '
SET @str_comando2 = @str_comando2 + ' queryout ' + @str_NomeArquivo2 + ' -c -t ";" -T';
select @str_comando2
Exec xp_cmdshell @str_comando2 

Exec xp_cmdshell 'bcp " SELECT RTRIM(LTRIM(CONVERT(CHAR,NRECNO))) AS NRECNO ,ADIANT ,RTRIM(LTRIM(CONVERT(CHAR,BASE_CMC))) AS BASE_CMC ,BASE_VND ,BCO_DEST ,RTRIM(LTRIM(CONVERT(CHAR,BONIFIC))) AS BONIFIC ,CGC ,RTRIM(LTRIM(CONVERT(CHAR,CHAVE))) AS CHAVE ,RTRIM(LTRIM(CONVERT(CHAR,CHAVE_CP))) AS CHAVE_CP ,CHEQUE ,COBR_FRET ,COD_ARE ,COD_BAN ,COD_CED ,RTRIM(LTRIM(CONVERT(CHAR,COD_CLI))) AS COD_CLI ,COD_COB ,COD_COMIS ,COD_CORR ,RTRIM(LTRIM(CONVERT(CHAR,COD_EMP))) AS COD_EMP ,COD_EVE ,COD_OPE ,COD_PAG ,COD_POS ,RTRIM(LTRIM(CONVERT(CHAR,COMISS_F))) AS COMISS_F ,COMISS_NEG ,RTRIM(LTRIM(CONVERT(CHAR,COMISS_R))) AS COMISS_R ,COMPL_OBRA ,CONTABILIZ ,CONTA_CORR ,DATA_CANHO ,DATA_DI ,DATA_EM ,DATA_EMIS ,DATA_FLUX ,RTRIM(LTRIM(CONVERT(CHAR,DATA_JUROS))) AS DATA_JUROS ,RTRIM(LTRIM(CONVERT(CHAR,DATA_MULTA))) AS DATA_MULTA ,DATA_OCOR ,DATA_PAGA ,DATA_SIMUL ,DATA_VENC ,RTRIM(LTRIM(CONVERT(CHAR,DDU))) AS DDU ,DOC ,EMBARQUE ,EMITIDO ,ESPEC_EXTR ,RTRIM(LTRIM(CONVERT(CHAR,FRETE))) AS FRETE ,HISTORICO ,HP ,HP_NFSERV ,INVEST01 ,JOB ,JUROS_COMP ,LOCAL ,LOTE_CTB ,MACRO ,MARCA ,MARCA_VOL ,MOD_TRANS ,MT_ATRAS ,NAO_CTBZ ,NCONHECIM ,NOMINAL ,NOTIFICA ,NR ,NR_DESPNF ,NUMERO ,NUMERO_DI ,NUMERO_NF ,N_BANCARIO ,N_VENDOR ,OBS ,OR_DS ,PED ,RTRIM(LTRIM(CONVERT(CHAR,PER_JUROS))) AS PER_JUROS ,RTRIM(LTRIM(CONVERT(CHAR,PER_MULTA))) AS PER_MULTA ,RTRIM(LTRIM(CONVERT(CHAR,PESO_NF))) AS PESO_NF ,PLACA ,POSCARNE ,PROCESSO ,PROJECAO ,QUANT_VOL ,RAT_CONTA ,RAT_JOB ,RAT_SCC ,REJEICAO ,RH ,SCC ,RTRIM(LTRIM(CONVERT(CHAR,SEGURO))) AS SEGURO ,SEM_GRADE ,SERIE ,SERIE_ANT ,RTRIM(LTRIM(CONVERT(CHAR,SITCARNE))) AS SITCARNE ,STTVND ,SWIFT ,RTRIM(LTRIM(CONVERT(CHAR,TAXA_CAMB))) AS TAXA_CAMB ,TIP ,TIPC ,TRANSPORT ,RTRIM(LTRIM(CONVERT(CHAR,TX_VND))) AS TX_VND ,UF_EXTR ,UM ,UM2 ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_ACRE))) AS VALOR_ACRE ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_ADIC))) AS VALOR_ADIC ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_APLI))) AS VALOR_APLI ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_CHEQ))) AS VALOR_CHEQ ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_DOC))) AS VALOR_DOC ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_DOCA))) AS VALOR_DOCA ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_INSS))) AS VALOR_INSS ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_IR))) AS VALOR_IR ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_ISS))) AS VALOR_ISS ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_LIV))) AS VALOR_LIV ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_MER))) AS VALOR_MER ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_TOT))) AS VALOR_TOT ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_TOTA))) AS VALOR_TOTA ,VALUE_DATE ,VENC_VND ,VENDOR ,APROVA_PCA ,APROVA_RA ,COD_PAG2 ,GRUPO ,JOB2 ,SCC2 ,USUARIO ,CONF_FRETE ,CONTAB_L02 ,CONTAB_L03 ,CONTAB_L04 ,CONTAB_L05 ,CUPOM ,LOTE_L02 ,LOTE_L03 ,LOTE_L04 ,LOTE_L05 ,NUM_ECF ,TIPOALIQ ,COD_MARCA ,AD_BLOQ ,AD_LIBE ,COD_USU ,DT_OCORBC ,HISTORICO2 ,PAGO_PCA ,PAGO_RA ,PCA ,UNID_NEG  ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_COFI))) AS VALOR_COFI ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_DESP))) AS VALOR_DESP ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_PIS))) AS VALOR_PIS ,SEMJRM ,IMG_NF ,NDEPOSITO ,DATA_CONC ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_FRUR))) AS VALOR_FRUR ,ENCONTRO ,IOFFIN ,REMVENDOR ,RTRIM(LTRIM(CONVERT(CHAR,TXCOMP))) AS TXCOMP ,RTRIM(LTRIM(CONVERT(CHAR,TXVEND))) AS TXVEND ,REGIAO_SGH ,RTRIM(LTRIM(CONVERT(CHAR,FRETE_COMP))) AS FRETE_COMP ,DT_SERASA ,DTAVSERASA ,RTRIM(LTRIM(CONVERT(CHAR,BASICMF))) AS BASICMF ,RTRIM(LTRIM(CONVERT(CHAR,FRTTERC))) AS FRTTERC ,RTRIM(LTRIM(CONVERT(CHAR,VLRICMF))) AS VLRICMF ,NDEPOSITO2 ,REGIAO_ANT ,RTRIM(LTRIM(CONVERT(CHAR,JUROS_ATRA))) AS JUROS_ATRA ,JUR_BAIXA ,ENV_THEO ,RTRIM(LTRIM(CONVERT(CHAR,VLR_SENAT))) AS VLR_SENAT ,RTRIM(LTRIM(CONVERT(CHAR,VALOR_CSLL))) AS VALOR_CSLL ,RELATO ,ALTER_VENC ,RTRIM(LTRIM(CONVERT(CHAR,VLR_CRCOFI))) AS VLR_CRCOFI ,RTRIM(LTRIM(CONVERT(CHAR,VLR_CRPIS))) AS VLR_CRPIS ,RTRIM(LTRIM(CONVERT(CHAR,VLR_INSS_E))) AS VLR_INSS_E ,DT_AVISO ,PROTESTO ,DT_PROTEST ,REM_LOGIST ,RTRIM(LTRIM(CONVERT(CHAR,VLR_ICMS_E))) AS VLR_ICMS_E ,RTRIM(LTRIM(CONVERT(CHAR,BASE_IRRF))) AS BASE_IRRF ,RTRIM(LTRIM(CONVERT(CHAR,SUBST_ICM))) AS SUBST_ICM ,RTRIM(LTRIM(CONVERT(CHAR,SUBST_ICMA))) AS SUBST_ICMA ,DT_CANCEL ,DT_AUDAC ,DT_ABE ,MUDA_BANCO ,COD_BANORI ,CONVENIO  ,RTRIM(LTRIM(CONVERT(CHAR,ENC_AUTONO))) AS ENC_AUTONO ,RTRIM(LTRIM(CONVERT(CHAR,FRT_BST))) AS FRT_BST ,RTRIM(LTRIM(CONVERT(CHAR,FRT_VST))) AS FRT_VST ,RTRIM(LTRIM(CONVERT(CHAR,FRT_FST))) AS FRT_FST ,RTRIM(LTRIM(CONVERT(CHAR,FRT_AST))) AS FRT_AST ,RTRIM(LTRIM(CONVERT(CHAR,FRT_TST))) AS FRT_TST ,DESMEMB ,COD_VEN ,COD_SUP ,RTRIM(LTRIM(CONVERT(CHAR,CHAVECF))) AS CHAVECF ,RTRIM(LTRIM(CONVERT(CHAR,IDLAN))) AS IDLAN ,IMG_NFE ,DT_CAALBOR ,RTRIM(LTRIM(CONVERT(CHAR,FRETE_PAG))) AS FRETE_PAG ,RTRIM(LTRIM(CONVERT(CHAR,FRT_PIS))) AS FRT_PIS ,RTRIM(LTRIM(CONVERT(CHAR,FRT_COFINS))) AS FRT_COFINS ,LPROVEST ,RTRIM(LTRIM(CONVERT(CHAR,ALIQ_IRFF))) AS ALIQ_IRFF ,RTRIM(LTRIM(CONVERT(CHAR,DEDUCAO))) AS DEDUCAO ,RTRIM(LTRIM(CONVERT(CHAR,PRV_COMISS))) AS PRV_COMISS ,RTRIM(LTRIM(CONVERT(CHAR,TOT_TRIB))) AS TOT_TRIB ,DT_BXPROV ,RTRIM(LTRIM(CONVERT(CHAR,CH_BX_COM))) AS CH_BX_COM ,RTRIM(LTRIM(CONVERT(CHAR,CH_BX_FRT))) AS CH_BX_FRT ,RET_ISS ,RTRIM(LTRIM(CONVERT(CHAR,DESCTO_AS))) AS DESCTO_AS ,RTRIM(LTRIM(CONVERT(CHAR,CMS_DUP))) AS CMS_DUP ,RTRIM(LTRIM(CONVERT(CHAR,ICMSFCP))) AS ICMSFCP ,RTRIM(LTRIM(CONVERT(CHAR,ICMSDIFA))) AS ICMSDIFA ,RTRIM(LTRIM(CONVERT(CHAR,ICMSDORI))) AS ICMSDORI ,RTRIM(LTRIM(CONVERT(CHAR,BX_PRVCOM))) AS BX_PRVCOM ,DATA_RECEB  FROM ##PAGREC "  queryout \\srv-sql-hml\d$\Temp\SMILE_BI\DADOS.CSV -c -t ";" -T'
--- UNIR ARQUIVOS
               
SET @sql = 'copy /V /A /B /D ' + @str_NomeArquivo
SET @SQL +='+'+@str_NomeArquivo2 
SET @SQL +=' '+@str_NomeArquivo3 

EXECUTE master..xp_cmdshell @sql

SET @sql = 'DEL ' + @str_NomeArquivo
EXECUTE master..xp_cmdshell @sql

SET @sql = 'DEL ' + @str_NomeArquivo2
EXECUTE master..xp_cmdshell @sql
