use NEWAGE

DECLARE @DATA_INI VARCHAR(10)
DECLARE @DATA_FIM VARCHAR(10)
SET @DATA_INI = CONVERT(DATE,DateAdd(mm, DateDiff(mm,0,GetDate()) , 0),112) 
SET @DATA_FIM = CONVERT(DATE,GETDATE()-1,100)
SET @DATA_INI = '07/01/2016'
SET @DATA_FIM = '12/31/2019'
--*/

DECLARE @str_NomeArquivo varchar(max)
DECLARE @str_NomeArquivo2 varchar(max)
DECLARE @str_NomeArquivo3 varchar(max)
DECLARE @str_comandocab VARCHAR(8000)
DECLARE @str_comando NVARCHAR(MAX)
DECLARE @str_comando2 VARCHAR(8000)
DECLARE @WORKDIR VARCHAR(200)
DECLARE @sql VARCHAR(200)   


IF OBJECT_ID('TEMPDB.DBO.##MOV_CON') IS NOT NULL DROP TABLE ##MOV_CON
SET @WORKDIR = '\\BRDCVPNAS001\smile\'
SET @str_NomeArquivo=@WORKDIR+'CAB_MOV.CSV'
SET @str_NomeArquivo2=@WORKDIR+'DADOS.CSV'
SET @str_NomeArquivo3=@WORKDIR+'MOV_CON.CSV'

SET @str_comando = 'SELECT '''
SELECT @str_comando += ''+(RTRIM(A.NAME)+';')  from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'MOV_CON' ) 
SET @str_comando = @str_comando + 'ID_ITEM'
--SET @str_comando = LEFT(@STR_COMANDO,LEN(@STR_COMANDO)-1)
select @str_comando = @str_comando + ''''

SET @str_comandocab = 'bcp " '+@str_comando
SET @str_comandocab = @str_comandocab + ' " '
SET @str_comandocab = @str_comandocab + ' queryout ' + @str_NomeArquivo + ' -c -t  -T';

Exec xp_cmdshell @str_comandocab 

SELECT @str_comandocab

---- AGORA BUSCA O CONTEUDO
/*
SET @str_comando = ''
SET @str_comando += ' SELECT '
SELECT @str_comando += case when RTRIM(LTRIM(b.name)) in ('char','varchar') then 'ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM('+A.NAME+'))),'''') AS '+A.NAME ELSE 
CASE WHEN RTRIM(LTRIM(b.name)) in ('text') THEN 'ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO((('+A.NAME+'))),'''') AS '+A.NAME ELSE A.NAME END END +' ,'  from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'MOV_CON' ) 
SET @str_comando = +LEFT(@STR_COMANDO,LEN(@STR_COMANDO)-1)
SET @str_comando += ' INTO ##MOV_CON'
SET @str_comando = @str_comando + ' FROM NEWAGE.DBO.MOV_CON WHERE EXTORNADO IS NULL AND DATA>=''06/28/2018'' AND DATA<=''06/28/2018'' '
SELECT @str_comando
EXECUTE SP_EXECUTESQL @str_comando
*/

SELECT NRECNO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(ACERTO))),'') AS ACERTO ,AL_ICMS ,AL_ICMSUBS ,AL_II ,AL_INSS ,AL_IPI ,AL_IRRF ,
AL_ISS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(ASSINATURA))),'') AS ASSINATURA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(AUTO))),'') AS AUTO ,
BASE_CMC ,BASE_ICMS ,BASE_IPI ,BASE_SUBST ,BASE_TCMC ,BASE_TCMCA ,BONIFIC ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CARGA))),'') AS CARGA ,CHAVE ,CHAVE_DEST ,CHAVE_ORIG ,
CHAVE_PED ,CLI_FOR ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CODIGO))),'') AS CODIGO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_FIS))),'') AS COD_FIS ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_ICM))),'') AS COD_ICM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_OPE))),'') AS COD_OPE ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_PAG))),'') AS COD_PAG ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_SER))),'') AS COD_SER ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_TRANS))),'') AS COD_TRANS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_TRI))),'') AS COD_TRI ,
COEF_SUBST ,COMISS_D ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COMPL_OBRA))),'') AS COMPL_OBRA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CONHEC))),'') AS CONHEC ,
CUSTO ,CUSTO_AGR ,CUS_ADIC ,DATA ,DESCTO ,DESC_PER ,DESTINO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(DOC))),'') AS DOC ,EMPRESA ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(EXTORNADO))),'') AS EXTORNADO ,FRETE ,INSS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(JOB))),'') AS JOB 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LIN1))),'') AS LIN1 ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOCAL))),'') AS LOCAL 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOCAL_TRAN))),'') AS LOCAL_TRAN ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOTE))),'') AS LOTE 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(MANUT))),'') AS MANUT ,MAT_DIR ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NF_COMPL))),'') AS NF_COMPL ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NUMERO))),'') AS NUMERO 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OP))),'') AS OP ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(PED))),'') AS PED ,PESO ,QTD_ELOS ,QUAN ,QUAN_CMC 
,QUAN_PC ,QUAN_REM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(RECEB))),'') AS RECEB ,RED_BASE ,RED_IPI ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(REQUIS))),'') AS REQUIS ,RETORNADO 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(SCC))),'') AS SCC ,SEQ ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(SERIE))),'') AS SERIE 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TIPO))),'') AS TIPO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TIPO_NUM))),'') AS TIPO_NUM 
,TOTAL_EX ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(UM))),'') AS UM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(UNID))),'') AS UNID ,VALOR_CALC ,VALOR_CIF 
,VALOR_CMC ,VALOR_DIFA ,VALOR_FOB ,VALOR_ICMS ,VALOR_INSS ,VALOR_IPI ,VALOR_IR ,VALOR_ISS ,VALOR_MOD ,VALOR_PRES ,VALOR_SUBS ,VALOR_TCMC ,VALOR_UNI 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOTE_CTBE))),'') AS LOTE_CTBE 
,CHAVEFASB ,QUAN_DESCE ,VALOR_TOT ,VAL_DESCE ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(USUARIO))),'') AS USUARIO ,ICMS_DIF 
,RECNO_COMP ,VLR_CRCOFI ,VLR_CRPIS ,IPI_PROV ,VLR_ICMS_E ,SUBST_ICM ,ICM_DISP ,QUAN_EST ,PER_COMIS ,VLR_INSS_E ,FRT_BST ,FRT_VST ,FRT_FST ,FRT_AST ,FRT_TST 
,PERC_0 ,PERC_1 ,PERC_2 ,PERC_3 ,PERC_4 ,PERC_QB ,CUSTO_IND ,PER_COMIS2 ,AL_MVA ,ISNULL(NEWAGE.DBO.
FN_TIRA_ACENTO(RTRIM(LTRIM(CODTRI_IPI))),'') AS CODTRI_IPI ,IPI_DEV ,FRETE_PAG ,ICMS_DEM ,ISENTO_ICM ,OUTROS_ICM ,ISENTO_IPI ,OUTROS_IPI ,VLR_DBCOFI ,VLR_DBPIS ,QTD_ICMS ,VAL_ICMS ,FRT_PIS ,FRT_COFINS 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CST_PIS))),'') AS CST_PIS 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CST_COF))),'') AS CST_COF ,VLR_SEGURO ,FRT_ICMDIF ,VALOR_ADIC ,FRETE_EMB ,PRV_COMISS ,CHV_PATRIM 
,ORIGEM ,QUAN_REV ,REC_ORIG ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OBSFCI))),'') AS OBSFCI ,TOT_TRIB 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NUMFCI))),'') AS NUMFCI ,FRT_DMC ,PIS_FDMC ,COF_FDMC ,ICM_FDMC ,DESCTO_AS ,VAL_FIXO 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OP_IND))),'') AS OP_IND ,CHAVE_IND ,SEQ_IND ,QT_PERC ,QT_QTD ,RT_PERC ,RT_QTD ,AL_INTD ,ICMS_DEST ,DIFAL ,AL_FCP 
,BCUFDEST ,ICMS_ORIG ,ICMS_FCP ,AL_PART ,BASEFCP ,FCP_EMBST ,IPI_RED ,ICM_ZFM ,FRT_ICMS ,VFIXO_TRF ,OVERP_TRF ,IPI_CUSTO ,EICM_TRF ,REC_RCBT2 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TP_CONS))),'') AS TP_CONS 
,VALOR_MER ,ORDEM_P,DBO.ZEROSESQUERDA(ROW_NUMBER() OVER(PARTITION BY CHAVE ORDER BY CODIGO),4)'ID_ITEM'
INTO ##MOV_CON
FROM NEWAGE.DBO.MOV_CON WITH (INDEX(MOV_CON_15)NOLOCK)
WHERE EXTORNADO IS NULL AND DATA>='07/01/2016' AND DATA<='07/02/2016'
AND LEFT(NUMERO,2)<>'TR' AND CHAVE IS NOT NULL
option (maxdop 1)

--SET @str_comando2 = 'bcp " SELECT * FROM ##MOV_CON'
--SET @str_comando2 = @str_comando2 + ' " '
--SET @str_comando2 = @str_comando2 + ' queryout ' + @str_NomeArquivo2 + ' -c -t ";" -T';
--select @str_comando2
--Exec xp_cmdshell @str_comando2 

/*
SET @str_comando2 = ''
SET @str_comando2 += ' bcp " SELECT '
SELECT @str_comando2 += case when RTRIM(LTRIM(b.name)) in ('NUMERIC','INT') then 'RTRIM(LTRIM(CONVERT(CHAR,'+A.NAME+'))) AS '+A.NAME ELSE 
A.NAME END +' ,'  
from sys.columns a inner join sys.types b on a.system_type_id = b.user_type_id
where a.object_id = ( SELECT OBJECT_ID FROM SYS.TABLES WHERE NAME = 'MOV_CON' ) 
--SET @str_comando2 = +LEFT(@STR_COMANDO2,LEN(@STR_COMANDO2)-1)
SET @str_comando2 = @str_comando2+'ID_ITEM'
SET @str_comando2 = @str_comando2 + ' FROM ##MOV_CON " '
SET @str_comando2 = @str_comando2 + ' queryout ' + @str_NomeArquivo2 + ' -c -t ";" -T';
select @str_comando2
Exec xp_cmdshell @str_comando2 
*/

Exec xp_cmdshell ' bcp " SELECT NRECNO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(ACERTO))),'') AS ACERTO ,AL_ICMS ,AL_ICMSUBS ,AL_II ,AL_INSS ,AL_IPI ,AL_IRRF ,AL_ISS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(ASSINATURA))),'') AS ASSINATURA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(AUTO))),'') AS AUTO ,BASE_CMC ,BASE_ICMS ,BASE_IPI ,BASE_SUBST ,BASE_TCMC ,BASE_TCMCA ,BONIFIC ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CARGA))),'') AS CARGA ,CHAVE ,CHAVE_DEST ,CHAVE_ORIG ,CHAVE_PED ,CLI_FOR ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CODIGO))),'') AS CODIGO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_FIS))),'') AS COD_FIS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_ICM))),'') AS COD_ICM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_OPE))),'') AS COD_OPE ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_PAG))),'') AS COD_PAG ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_SER))),'') AS COD_SER ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_TRANS))),'') AS COD_TRANS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_TRI))),'') AS COD_TRI ,COEF_SUBST ,COMISS_D ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COMPL_OBRA))),'') AS COMPL_OBRA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CONHEC))),'') AS CONHEC ,CUSTO ,CUSTO_AGR ,CUS_ADIC ,DATA ,DESCTO ,DESC_PER ,DESTINO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(DOC))),'') AS DOC ,EMPRESA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(EXTORNADO))),'') AS EXTORNADO ,FRETE ,INSS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(JOB))),'') AS JOB ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LIN1))),'') AS LIN1 ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOCAL))),'') AS LOCAL ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOCAL_TRAN))),'') AS LOCAL_TRAN ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOTE))),'') AS LOTE ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(MANUT))),'') AS MANUT ,MAT_DIR ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NF_COMPL))),'') AS NF_COMPL ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NUMERO))),'') AS NUMERO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OP))),'') AS OP ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(PED))),'') AS PED ,PESO ,QTD_ELOS ,QUAN ,QUAN_CMC ,QUAN_PC ,QUAN_REM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(RECEB))),'') AS RECEB ,RED_BASE ,RED_IPI ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(REQUIS))),'') AS REQUIS ,RETORNADO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(SCC))),'') AS SCC ,SEQ ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(SERIE))),'') AS SERIE ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TIPO))),'') AS TIPO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TIPO_NUM))),'') AS TIPO_NUM ,TOTAL_EX ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(UM))),'') AS UM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(UNID))),'') AS UNID ,VALOR_CALC ,VALOR_CIF ,VALOR_CMC ,VALOR_DIFA ,VALOR_FOB ,VALOR_ICMS ,VALOR_INSS ,VALOR_IPI ,VALOR_IR ,VALOR_ISS ,VALOR_MOD ,VALOR_PRES ,VALOR_SUBS ,VALOR_TCMC ,VALOR_UNI ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOTE_CTBE))),'') AS LOTE_CTBE ,CHAVEFASB ,QUAN_DESCE ,VALOR_TOT ,VAL_DESCE ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(USUARIO))),'') AS USUARIO ,ICMS_DIF ,RECNO_COMP ,VLR_CRCOFI ,VLR_CRPIS ,IPI_PROV ,VLR_ICMS_E ,SUBST_ICM ,ICM_DISP ,QUAN_EST ,PER_COMIS ,VLR_INSS_E ,FRT_BST ,FRT_VST ,FRT_FST ,FRT_AST ,FRT_TST ,PERC_0 ,PERC_1 ,PERC_2 ,PERC_3 ,PERC_4 ,PERC_QB ,CUSTO_IND ,PER_COMIS2 ,AL_MVA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CODTRI_IPI))),'') AS CODTRI_IPI ,IPI_DEV ,FRETE_PAG ,ICMS_DEM ,ISENTO_ICM ,OUTROS_ICM ,ISENTO_IPI ,OUTROS_IPI ,VLR_DBCOFI ,VLR_DBPIS ,QTD_ICMS ,VAL_ICMS ,FRT_PIS ,FRT_COFINS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CST_PIS))),'') AS CST_PIS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CST_COF))),'') AS CST_COF ,VLR_SEGURO ,FRT_ICMDIF ,VALOR_ADIC ,FRETE_EMB ,PRV_COMISS ,CHV_PATRIM ,ORIGEM ,QUAN_REV ,REC_ORIG ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OBSFCI))),'') AS OBSFCI ,TOT_TRIB ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NUMFCI))),'') AS NUMFCI ,FRT_DMC ,PIS_FDMC ,COF_FDMC ,ICM_FDMC ,DESCTO_AS ,VAL_FIXO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OP_IND))),'') AS OP_IND ,CHAVE_IND ,SEQ_IND ,QT_PERC ,QT_QTD ,RT_PERC ,RT_QTD ,AL_INTD ,ICMS_DEST ,DIFAL ,AL_FCP ,BCUFDEST ,ICMS_ORIG ,ICMS_FCP ,AL_PART ,BASEFCP ,FCP_EMBST ,IPI_RED ,ICM_ZFM ,FRT_ICMS ,VFIXO_TRF ,OVERP_TRF ,IPI_CUSTO ,EICM_TRF ,REC_RCBT2 ,TP_CONS AS TP_CONS ,VALOR_MER ,ORDEM_P,ID_ITEM FROM ##MOV_CON"  queryout \\BRDCVPNAS001\smile\DADOS.CSV -c -t ";" -T'

/*
Exec xp_cmdshell ' bcp " SELECT NRECNO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(ACERTO))),'') AS ACERTO ,AL_ICMS ,AL_ICMSUBS ,AL_II ,AL_INSS ,AL_IPI ,AL_IRRF ,
AL_ISS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(ASSINATURA))),'') AS ASSINATURA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(AUTO))),'') AS AUTO ,
BASE_CMC ,BASE_ICMS ,BASE_IPI ,BASE_SUBST ,BASE_TCMC ,BASE_TCMCA ,BONIFIC ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CARGA))),'') AS CARGA ,CHAVE ,CHAVE_DEST ,CHAVE_ORIG ,
CHAVE_PED ,CLI_FOR ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CODIGO))),'') AS CODIGO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_FIS))),'') AS COD_FIS ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_ICM))),'') AS COD_ICM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_OPE))),'') AS COD_OPE ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_PAG))),'') AS COD_PAG ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_SER))),'') AS COD_SER ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_TRANS))),'') AS COD_TRANS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COD_TRI))),'') AS COD_TRI ,
COEF_SUBST ,COMISS_D ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(COMPL_OBRA))),'') AS COMPL_OBRA ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CONHEC))),'') AS CONHEC ,
CUSTO ,CUSTO_AGR ,CUS_ADIC ,DATA ,DESCTO ,DESC_PER ,DESTINO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(DOC))),'') AS DOC ,EMPRESA ,
ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(EXTORNADO))),'') AS EXTORNADO ,FRETE ,INSS ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(JOB))),'') AS JOB 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LIN1))),'') AS LIN1 ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOCAL))),'') AS LOCAL 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOCAL_TRAN))),'') AS LOCAL_TRAN ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOTE))),'') AS LOTE 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(MANUT))),'') AS MANUT ,MAT_DIR ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NF_COMPL))),'') AS NF_COMPL ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NUMERO))),'') AS NUMERO 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OP))),'') AS OP ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(PED))),'') AS PED ,PESO ,QTD_ELOS ,QUAN ,QUAN_CMC 
,QUAN_PC ,QUAN_REM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(RECEB))),'') AS RECEB ,RED_BASE ,RED_IPI ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(REQUIS))),'') AS REQUIS ,RETORNADO 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(SCC))),'') AS SCC ,SEQ ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(SERIE))),'') AS SERIE 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TIPO))),'') AS TIPO ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TIPO_NUM))),'') AS TIPO_NUM 
,TOTAL_EX ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(UM))),'') AS UM ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(UNID))),'') AS UNID ,VALOR_CALC ,VALOR_CIF 
,VALOR_CMC ,VALOR_DIFA ,VALOR_FOB ,VALOR_ICMS ,VALOR_INSS ,VALOR_IPI ,VALOR_IR ,VALOR_ISS ,VALOR
_MOD ,VALOR_PRES ,VALOR_SUBS ,VALOR_TCMC ,VALOR_UNI ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(LOTE_CTBE))),'') AS LOTE_CTBE 
,CHAVEFASB ,QUAN_DESCE ,VALOR_TOT ,VAL_DESCE ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(USUARIO))),'') AS USUARIO ,ICMS_DIF 
,RECNO_COMP ,VLR_CRCOFI ,VLR_CRPIS ,IPI_PROV ,VLR_ICMS_E ,SUBST_ICM ,ICM_DISP ,QUAN_EST ,PER_COMIS ,VLR_INSS_E ,FRT_BST ,FRT_VST ,FRT_FST ,FRT_AST ,FRT_TST 
,PERC_0 ,PERC_1 ,PERC_2 ,PERC_3 ,PERC_4 ,PERC_QB ,CUSTO_IND ,PER_COMIS2 ,AL_MVA ,ISNULL(NEWAGE.DBO.
FN_TIRA_ACENTO(RTRIM(LTRIM(CODTRI_IPI))),'') AS CODTRI_IPI ,IPI_DEV ,FRETE_PAG ,ICMS_DEM ,ISENTO_ICM ,OUTROS_ICM ,ISENTO_IPI ,OUTROS_IPI ,VLR_DBCOFI ,VLR_DBPIS ,QTD_ICMS ,VAL_ICMS ,FRT_PIS ,FRT_COFINS 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CST_PIS))),'') AS CST_PIS 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(CST_COF))),'') AS CST_COF ,VLR_SEGURO ,FRT_ICMDIF ,VALOR_ADIC ,FRETE_EMB ,PRV_COMISS ,CHV_PATRIM 
,ORIGEM ,QUAN_REV ,REC_ORIG ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OBSFCI))),'') AS OBSFCI ,TOT_TRIB 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(NUMFCI))),'') AS NUMFCI ,FRT_DMC ,PIS_FDMC ,COF_FDMC ,ICM_FDMC ,DESCTO_AS ,VAL_FIXO 
,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(OP_IND))),'') AS OP_IND ,CHAVE_IND ,SEQ_IND ,QT_PERC ,QT_QTD ,RT_
PERC ,RT_QTD ,AL_INTD ,ICMS_DEST ,DIFAL ,AL_FCP ,BCUFDEST ,ICMS_ORIG ,ICMS_FCP ,AL_PART ,BASEFCP ,FCP_EMBST ,IPI_RED ,ICM_ZFM ,FRT_ICMS ,VFIXO_TRF ,
OVERP_TRF ,IPI_CUSTO ,EICM_TRF ,REC_RCBT2 ,ISNULL(NEWAGE.DBO.FN_TIRA_ACENTO(RTRIM(LTRIM(TP_CONS))),'') AS TP_CONS 
,VALOR_MER ,ORDEM_P,ID_ITEM FROM ##MOV_CON"  queryout \\BRDCVPNAS001\smile\DADOS.CSV -c -t ";" -T'
*/

--- UNIR ARQUIVOS
               
SET @sql = 'copy /V /A /B /D ' + @str_NomeArquivo
SET @SQL +='+'+@str_NomeArquivo2 
SET @SQL +=' '+@str_NomeArquivo3 

EXECUTE master..xp_cmdshell @sql

SET @sql = 'DEL ' + @str_NomeArquivo
EXECUTE master..xp_cmdshell @sql

SET @sql = 'DEL ' + @str_NomeArquivo2
EXECUTE master..xp_cmdshell @sql

