

sp_helptext GERA_ZIP_SMILE_BI


USE NEWAGE

EXEC GERA_ZIP_SMILE_BI

ALTER PROC GERA_ZIP_SMILE_BI
AS

SET NOCOUNT ON

DECLARE @source VARCHAR(1000),
        @destination VARCHAR(1000),
        @Command VARCHAR(1000)
DECLARE @DATAHORA		VARCHAR(16)
DECLARE @NOMEARQ		VARCHAR(45)
DECLARE @RETORNO		VARCHAR(20)
DECLARE @CONTADOR		INT

DECLARE @FILES TABLE (ID INT IDENTITY, FILENAME VARCHAR(500))                   

--SET @source = '\\srv-sql-hml\d$\Temp\*.CSV'
SET @source = '\\srv-sql-hml\d$\Temp\SMILE_BI\*.CSV'

SET @DATAHORA = CONVERT(VARCHAR,YEAR(GETDATE()))+DBO.ZEROSESQUERDA(MONTH(GETDATE()),2)+DBO.ZEROSESQUERDA(DAY(GETDATE()),2)+REPLACE(REPLACE(SUBSTRING(CONVERT(VARCHAR,CONVERT(TIME,GETDATE(),108)),1,11),':',''),'.','')
SET @NOMEARQ = @DATAHORA+'_coreBuilder_SmileBIData.zip'
SET @destination = '\\srv-sql-hml\d$\Temp\SMILE_BI\'+@NOMEARQ
--SET @destination = 'E:\Temp\testRar.rar'

SET @Command = '"C:\Program Files\WinRAR\Rar.exe"  a -m5 -ep1 ' +@destination+' '+@source

--EXEC MASTER..xp_cmdshell @Command

INSERT INTO @FILES  EXEC MASTER..xp_cmdshell @Command

IF OBJECT_ID('TEMPDB.DBO.#DIR') IS NOT NULL DROP TABLE #DIR                     
SELECT * INTO #DIR                                                              
FROM @FILES   

DELETE FROM #DIR WHERE FILENAME IS NULL OR FILENAME='File Not Found'


SELECT @CONTADOR = COUNT(*) FROM #DIR WHERE FILENAME ='done'

IF @CONTADOR >0
BEGIN
	SET @RETORNO =  1 --'ARQUIVO GERADO'
END
ELSE
BEGIN
	SET @RETORNO = 0 --'FALHA NO ARQUIVO'
END

SELECT @RETORNO






DECLARE @DATAHORA		VARCHAR(16)
DECLARE @NOMEARQ		VARCHAR(42)

SET @DATAHORA = CONVERT(VARCHAR,YEAR(GETDATE()))+DBO.ZEROSESQUERDA(MONTH(GETDATE()),2)+DBO.ZEROSESQUERDA(DAY(GETDATE()),2)+REPLACE(REPLACE(SUBSTRING(CONVERT(VARCHAR,CONVERT(TIME,GETDATE(),108)),1,11),':',''),'.','')
SET @NOMEARQ = @DATAHORA+'_coreBuilder_SmileBIData.zip'
SET @destination = '\\srv-sql-hml\d$\Temp\'+@NOMEARQ


-------------------------------------------------------ftp

CREATE PROC WEB2_GERA_PEDIDO_TXT @PED VARCHAR(10),@LOK INT OUTPUT
AS

SET NOCOUNT ON

--DECLARE @PED			VARCHAR(10)
--SET @PED = 'P1737032'

DECLARE @CARGA			VARCHAR(15)
Declare @cCmd_Txt       Varchar(200)
Declare @nRet			INT
Declare @cErroMsg		VARCHAR(200)
DECLARE @cDelimita      CHAR(1)
DECLARE @NOMETEMP		VARCHAR(20)
DECLARE @PATH			VARCHAR(100)
DECLARE @REC			INT
DECLARE @NOMEARQ		VARCHAR(100)

DECLARE @FTPSERVER		VARCHAR(128) 
DECLARE @FTPUSER		VARCHAR(128) 
DECLARE @FTPPWD			VARCHAR(128) 
DECLARE @FTPPATH		VARCHAR(128) 
DECLARE @WORKDIR		VARCHAR(128)
DECLARE @PESQARQ		VARCHAR(30)
DECLARE	@CMD			VARCHAR(1000)
DECLARE @WORKFILENAME	VARCHAR(128)
--DECLARE @LOK			INT
DECLARE @TEXTO			NVARCHAR(4000)

SELECT @REC = NRECNO ,
       @CARGA = NUM_CARGA
FROM PEDIDO WITH (NOLOCK)
WHERE PED =@PED

SET @cDelimita = '|'
SET @NOMEARQ = 'O3000EXI'+dbo.zerosesquerda(@REC,13)+'.D3'
--'\\10.0.0.130\f\CoreBuilder\Aplica\Producao\TOTAL_INTERFACES\PEDIDOS\'
SELECT @PATH=PATH_TOT+'PEDIDOS\'+@NOMEARQ FROM PARAMETROS_GLOBAIS

IF OBJECT_ID('TEMPDB.DBO.##ARQUIVO') IS NOT NULL DROP TABLE ##ARQUIVO
SELECT SPACE(563)'TEXTO',@REC AS REC
INTO ##ARQUIVO

--SELECT * FROM ##ARQUIVO

TRUNCATE TABLE ##ARQUIVO

INSERT INTO ##ARQUIVO
select 'ZISDI004'+space(1) +'1'+space(1)+space(10),@REC

INSERT INTO ##ARQUIVO
SELECT '#'+SPACE(562),@REC

INSERT INTO ##ARQUIVO
SELECT DBO.ESPACODIREITA('ZIPO',20,' ')+
DBO.ESPACODIREITA('1000',20,' ')+
DBO.ESPACODIREITA('20',20,' ')+
DBO.ESPACODIREITA('59',20,' ')+
DBO.ESPACODIREITA('CODIGO_SAP',20,' ')+
DBO.ESPACODIREITA(ISNULL(A.NUM_CARGA,''),40,' ')+

DBO.ESPACODIREITA(ISNULL(A.PED,''),20,' ')+

DBO.ESPACODIREITA(ISNULL(A.NUM_CARGA,''),40,' ')+
DBO.ESPACODIREITA('PAGAMENTO_SAP',20,'')+
DBO.ESPACODIREITA(ISNULL(A.TPFRETE,''),20,' ')+
DBO.ESPACODIREITA(ISNULL(B.CIDADE,''),20,' ')+
SPACE(20)+
DBO.ESPACODIREITA('ZSTK',20,' ')+
SPACE(92)+
'X',@REC
FROM PEDIDO A WITH (NOLOCK) INNER JOIN CLIENTES B WITH (NOLOCK) ON A.CLIENTE = B.XCLIENTES
WHERE A.PED = @PED

--select * from ##ARQUIVO

INSERT INTO ##ARQUIVO
SELECT 
--DBO.ESPACODIREITA(D.CODPFORN,20,'')+
DBO.ESPACODIREITA('T10500155',20,' ')+
DBO.ESPACODIREITA(CONVERT(VARCHAR(20),CONVERT(NUMERIC(17,3),ISNULL(B.QUAN_REM,0)+ISNULL(B.QUAN,0))),20,' ')+
DBO.ESPACODIREITA(B.UNID,20,' ')+
SPACE(20)+
DBO.ESPACODIREITA('Y2',20,' ')+
DBO.ESPACODIREITA((CASE WHEN C.ESTADO='MG' THEN '5101AA' ELSE '6101AA' END),20,' ')+
DBO.ESPACODIREITA(CONVERT(VARCHAR(20),CONVERT(NUMERIC(17,3),ISNULL(B.VALOR_UNI,0))),20,' ')+
DBO.ESPACODIREITA(CONVERT(VARCHAR(20),CONVERT(NUMERIC(17,3),ISNULL(A.TAXA_JUROS,0))),20,' ')+
DBO.ESPACODIREITA('0.000',20,' ')+
DBO.ESPACODIREITA(CONVERT(VARCHAR(20),CONVERT(NUMERIC(17,3),ISNULL(B.FRETE_UNIT,0))),20,' ')+
DBO.ESPACODIREITA(CONVERT(VARCHAR(20),CONVERT(NUMERIC(17,3),ISNULL(B.PER_COMIS,0))),20,' ')+
DBO.ESPACODIREITA('0.000',20,' ')+
DBO.ESPACODIREITA('0.000',20,' ')+
DBO.ESPACODIREITA('0.000',20,' ')+
DBO.ESPACODIREITA('1100',20,' ')+
DBO.ESPACODIREITA('0.000',20,' ')+'X',@REC
FROM PEDIDO A WITH (NOLOCK) INNER JOIN MOV_PED B WITH (NOLOCK) ON A.PED = B.PED
INNER JOIN CLIENTES C WITH (NOLOCK) ON A.CLIENTE = C.XCLIENTES
LEFT OUTER JOIN NFE_PRODFORN D WITH (NOLOCK) ON B.CODIGO = D.CODNEW
WHERE A.PED =@PED

--- FAZER VALIDACOES AQUI


--select @cCmd_txt='bcp ''select * from newage.dbo.regiao_sgh'' queryout \\BRNB0176\C$\TEMP\TESTE_MANUAL.TXT -c -SSVDEDB01 -T '
--select @cCmd_txt='bcp "select * from ##ARQUIVO" queryout \\10.0.0.130\f\CoreBuilder\Aplica\Producao\TOTAL_INTERFACES\CLIENTES\TESTE_MANUAL.TXT -c -SSVDEDB01 -T '
SELECT @CCMD_TXT='bcp "select TEXTO from ##ARQUIVO WHERE REC = ' + CONVERT(VARCHAR(10),@REC) + '" queryout ' + @PATH + ' -c -SSVDEDB01 -T '
EXEC MASTER.DBO.XP_CMDSHELL @CCMD_TXT,NO_OUTPUT

--select * from ##ARQUIVO
--print @PATH

SET @FTPPath = 'expansion' 
SET @WORKDIR = '\\10.0.0.130\F\COREBUILDER\APLICA\PRODUCAO\TOTAL_INTERFACES\PEDIDOS\'
set @FTPServer = 'ftp.totalalimentos.com.br' 
set @FTPUser = 'invivo' 
set @FTPPWD = 'ds7!4aBONE3!' 
set @WORKFILENAME = 'FTPCOPIAARQUIVO.BAT'

-- DEAL WITH SPECIAL CHARACTERS FOR ECHO COMMANDS

SELECT @FTPSERVER = REPLACE(REPLACE(REPLACE(@FTPSERVER, '|', '^|'),'<','^<'),'>','^>')
SELECT @FTPUSER = REPLACE(REPLACE(REPLACE(@FTPUSER, '|', '^|'),'<','^<'),'>','^>')
SELECT @FTPPWD = REPLACE(REPLACE(REPLACE(@FTPPWD, '|', '^|'),'<','^<'),'>','^>')
SELECT @FTPPATH = REPLACE(REPLACE(REPLACE(@FTPPATH, '|', '^|'),'<','^<'),'>','^>')

SELECT	@CMD = 'ECHO '					+ 'OPEN ' + @FTPSERVER
		+ ' > ' + @WORKDIR + @WORKFILENAME
EXEC MASTER..XP_CMDSHELL @CMD, NO_OUTPUT  

SELECT	@CMD = 'ECHO '					+ @FTPUSER
		+ '>> ' + @WORKDIR + @WORKFILENAME
EXEC MASTER..XP_CMDSHELL @CMD, NO_OUTPUT  

SELECT	@CMD = 'ECHO '					+ @FTPPWD
		+ '>> ' + @WORKDIR + @WORKFILENAME
EXEC MASTER..XP_CMDSHELL @CMD, NO_OUTPUT  

SELECT	@CMD = 'ECHO '					+ 'CD ' + @FTPPATH
		+ ' >> ' + @WORKDIR + @WORKFILENAME
EXEC MASTER..XP_CMDSHELL @CMD, NO_OUTPUT  

SELECT	@CMD = 'ECHO '					+ 'send ' + @PATH
		+ ' >> ' + @WORKDIR + @WORKFILENAME
EXEC MASTER..XP_CMDSHELL @CMD, NO_OUTPUT  

--SELECT	@CMD = 'ECHO '					+ 'ls -la '
SELECT	@CMD = 'ECHO '					+ 'ls '+ @NOMEARQ
		+ ' >> ' + @WORKDIR + @WORKFILENAME
EXEC MASTER..XP_CMDSHELL @CMD, NO_OUTPUT  

SELECT	@CMD = 'ECHO '					+ 'quit'
		+ ' >> ' + @WORKDIR + @WORKFILENAME
EXEC MASTER..XP_CMDSHELL @CMD, NO_OUTPUT  

SELECT @CMD = 'ftp -s:' + @WORKDIR + @WORKFILENAME

--PRINT @CMD

--EXEC MASTER..XP_CMDSHELL @CMD

IF OBJECT_ID('TEMPDB.DBO.#FTP') IS NOT NULL DROP TABLE #FTP
CREATE TABLE #FTP (ID INT IDENTITY(1,1), DIR VARCHAR(1000))
INSERT #FTP
EXEC MASTER..XP_CMDSHELL @CMD

--SELECT * FROM #FTP

SELECT @LOK = COUNT(*) FROM #FTP
where ID = 2 AND DIR IS NOT NULL

IF @LOK = 0
BEGIN

	SET @TEXTO = 'O pedido '+@PED+' da carga ' +@CARGA+' .Não foram enviados para o FTP da TOTAL !!!! ' + CHAR(10) + CHAR(13)
	SET @TEXTO = @TEXTO + 'O envio pode ter perdido conexão, envie pelo corebuilder, por pedido.' + CHAR(10) + CHAR(13)	

	EXEC msdb.dbo.sp_send_dbmail
	@profile_name = 'Banco SQL',
	@recipients = 'ricardo_silva@invivo-nsa.com.br',
	@body = @TEXTO,
	@subject = 'Existe(m) pedido(s) da Total que não foram enviados via FTP.VERIFIQUE!!!' ;

END

--PRINT @LOK

RETURN @LOK


